/*-------------------------------------------------------------------------+
|                                                                          |
| Copyright 2005-2011 The ConQAT Project                                   |
|                                                                          |
| Licensed under the Apache License, Version 2.0 (the "License");          |
| you may not use this file except in compliance with the License.         |
| You may obtain a copy of the License at                                  |
|                                                                          |
|    http://www.apache.org/licenses/LICENSE-2.0                            |
|                                                                          |
| Unless required by applicable law or agreed to in writing, software      |
| distributed under the License is distributed on an "AS IS" BASIS,        |
| WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. |
| See the License for the specific language governing permissions and      |
| limitations under the License.                                           |
+-------------------------------------------------------------------------*/
package org.conqat.engine.html_presentation;

import org.conqat.lib.commons.assessment.Assessment;
import org.conqat.lib.commons.clone.DeepCloneException;
import org.conqat.lib.commons.clone.IDeepCloneable;

/**
 * This interface describes the transport objects generated by different
 * layouter classes and presentation-internal page generators.
 * 
 * @author $Author: kinnen $
 * @version $Rev: 41751 $
 * @ConQAT.Rating GREEN Hash: CB2B35DA80383610D8F0CE3FAE240807
 */
public interface IPageDescriptor extends IDeepCloneable {

	/**
	 * Get summary for this result. May be <code>null</code>. Special objects
	 * like {@link Assessment}s are rendered accordingly on the overview page.
	 * For others, <code>toString()</code> is used.
	 */
	public Object getSummary();

	/** Get the HTML description of this result. */
	public String getContent();

	/** Get prose description of this result. */
	public String getDescription();

	/** Get name of the output file. */
	public String getFilename();

	/** Get name of the group this page belongs to. */
	public String getGroupId();

	/**
	 * Get the name of the icon associated with this result. Must return
	 * filename without path.
	 */
	public String getIconName();

	/** Get the name of this result. */
	public String getName();

	/** Flag that indicates whether page gets generated by ConQAT or is external */
	public boolean isExternal();
	
	/** {@inheritDoc} */
	@Override
	public IPageDescriptor deepClone() throws DeepCloneException;

}